api_core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /api

api_login_check:
    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/readme
    options: { i18n: false }