<?php

namespace CoreBundle\Repository;

/**
 * BaremeCoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaremeCoteRepository extends \Doctrine\ORM\EntityRepository
{
}
