<?php

namespace CoreBundle\Repository;

/**
 * PariFaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PariFaitRepository extends \Doctrine\ORM\EntityRepository
{
}
