<?php

namespace CoreBundle\Repository;

/**
 * PariDispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PariDispoRepository extends \Doctrine\ORM\EntityRepository
{
}
