<?php

namespace CoreBundle\Repository;

/**
 * PariDispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PariDispoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByDate()
    {
        $date = new \DateTime();

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM CoreBundle:PariDispo p where p.date>:date'
            )
            ->setParameter("date", $date)
            ->getResult();
    }
}
